name: Checks

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Grant access to private registry
        shell: bash
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Install dependencies
        run: npm ci --legacy-peer-deps --ignore-scripts
      - name: Test
        run: npm test
      - name: Lint
        run: npm run lint
